### Pandas: Work with lines! [Homework]
> ** You must import all the necessary packages yourself. **

> ** Write the code only where it is shown for recording. Do not delete comments! **


### Step 1

Please write the function `` `Load_Data (Filename)` ``, which will download data from the CSV file to the list of lists. Please write the function `` Load_Data (Filename) `` `, which will download data from the CSV file to` `Dataframe``` '. The file is `` num_house_Prices.csv`` 'provided with this Jupyter Notebook.


**Note:**

* If the file name is defined incorrectly, the function is `` Load_Data`` 'The following error message should display:

```{имя файла} does not exist```
* ```str_house_prices.csv``` - это csv-файл, который является результатом вашей предыдущей домашней работы.

In [1]:
# Начало вашего кода
import pandas as pd
import os.path

def load_data(filename):
    # check if file exists
    if not os.path.exists(filename):
        print(f"{filename} does not exist")
        return None
    
    # Конец вашего кода
    pd_data = pd.read_csv(filename)
    return pd_data

In [2]:
filename = "./SocialNetworkAds.csv"
data = load_data(filename=filename)
print(data)

./SocialNetworkAds.csv does not exist
None


### Ожидаемый результат:

```
./SocialNetworkAds.csv does not exist
```

In [3]:
print(data)

None


### Ожидаемый результат:

```
None
```

In [4]:
filename = "./dirty_str_house_prices.csv"
data = load_data(filename=filename)

In [5]:
print(data.columns.values.tolist())

['Unnamed: 0', 'Id', 'MSZoning', 'Street', 'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual', 'Functional', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'PavedDrive', 'SaleType', 'SaleCondition']


### Ожидаемый результат:

```
['Id', 'MSZoning', 'Street', 'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual', 'Functional', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'PavedDrive', 'SaleType', 'SaleCondition']
```

In [6]:
data

Unnamed: 0    Id MSZoning  Street LotShape LandContour Utilities  \
0              0     1      rl:   PAVE.     ;REg       \tlvl   AllPub.   
1              1     2    ...RL   <PAVE    reg\t        Lvl;  AllPUb\t   
2              2     3     ;Rl    Pave      ir1?        LVL!   Allpub!   
3              3     4       rl   pave.     ;IR1        .Lvl  ;ALLPUB;   
4              4     5    .rl\t  PaVE\t   Ir1...        Lvl<   !Allpub   
...          ...   ...      ...     ...      ...         ...       ...   
1333        1333  1456      ?rl   PAVE>   ...Reg       >LVL<  Allpub\t   
1334        1334  1457      Rl<   <PAVE      REG      ...lvl   Allpub:   
1335        1335  1458      ?RL   Pave!   ...Reg        >LVL   AlLPUb.   
1336        1336  1459     RL\t   PAvE<     reg;      ?lvl\t   .AlLPUb   
1337        1337  1460     .rl!  <Pave:     Reg;     ...LVL?  .AlLPUb    

       LotConfig LandSlope Neighborhood  ... Electrical KitchenQual  \
0        InsidE:      gtl      COLLGCR<  ...     SBRKr         gd\t   
1           FR2       Gtl<    veenker\t  ...    \tSBRKR         ta?   
2       ?inside     ...Gtl     ?COLLGCR  ...     sbrkr<         .Gd   
3        >Corner      ;GTL     .CRAWFOR  ...    \tSbrkr         Gd<   
4           ?fr2   .GTL...    ?NoRIdge>  ...    \tSbrkr         GD;   
...          ...       ...          ...  ...        ...         ...   
1333  ...INSIDe:      GTL;   \tGilbert:  ...     >sbrkr         .ta   
1334     .INsIDE      Gtl.    ...NWAMEs  ...      SBRKR         TA!   
1335     !InSiDE      >GTl    >CRAWfoR<  ...     Sbrkr;         !Gd   
1336     Inside:      :Gtl        names  ...   \tFUseA:         Gd!   
1337     INsIDe.    gtl...    \tEdwards  ...    ;SBRKR?        ;ta:   

     Functional GarageType GarageFinish GarageQual GarageCond PavedDrive  \
0           TYP    AttChd<         .RFn       TA\t      \tTA<         y?   
1          ;TYP    Attchd>        RFn\t       \tTa      >TA\t        ;Y!   
2        TyP...    Attchd;         ;RFN    \tTA...        TA           Y   
3          !TYP  DETCHD...         UNF?      \tTa;        ;Ta         .Y   
4         <Typ>   Attchd\t        !rfn>       TA\t         Ta       \tY>   
...         ...        ...          ...        ...        ...        ...   
1333       !TYP    ;Attchd         :RFn        TA<        :Ta         Y;   
1334      MIn1?    ATTCHD<         :unf       >Ta>        ?TA       >Y\t   
1335       :TyP    AttChD<         ?Rfn        >TA       :TA:         .Y   
1336        TYP    attchd.          Unf       :Ta;       \tTA       ...Y   
1337       typ:    .ATTCHD          FIn       >ta?      \tta<      >y...   

     SaleType SaleCondition  
0         wd      \tNormal?  
1         Wd        Normal.  
2         WD;        NORMAL  
3         wd.     ABNORML\t  
4        ?WD!       NoRmAl>  
...       ...           ...  
1333      Wd?     normal...  
1334      Wd;     \tNormal;  
1335     >wd!      :NORMAL;  
1336     <WD!       :normal  
1337      Wd;       ;NORMAL  

[1338 rows x 40 columns]

**Распечатайте первые и последние 5 строк pandas.DataFrame:**

In [7]:
# Начало вашего кода
import pandas as pd
import re

if "Unnamed: 0" in data.columns:
    data = data.drop(columns=["Unnamed: 0"])

def clean_text(text):
    if pd.isna(text):
        return "Unknown"
    text = str(text).strip()        
    text = re.sub(r"\s+", " ", text) 
    text = re.sub(r"[^A-Za-z0-9 ]", "", text)
    
    if text.isupper():
        return text
    return text.capitalize()

for col in data.select_dtypes(include=["object"]).columns:
    data[col] = data[col].apply(clean_text)

print(data.head())
print(data.tail())
#Конец вашего кода

   Id MSZoning Street LotShape LandContour Utilities LotConfig LandSlope  \
0   1       Rl   PAVE      Reg         Lvl    Allpub    Inside       Gtl   
1   2       RL   PAVE      Reg         Lvl    Allpub       FR2       Gtl   
2   3       Rl   Pave      Ir1         LVL    Allpub    Inside       Gtl   
3   4       Rl   Pave      IR1         Lvl    ALLPUB    Corner       GTL   
4   5       Rl   Pave      Ir1         Lvl    Allpub       Fr2       GTL   

  Neighborhood Condition1  ... Electrical KitchenQual Functional GarageType  \
0      COLLGCR       Norm  ...      Sbrkr          Gd        TYP     Attchd   
1      Veenker      Feedr  ...      SBRKR          Ta        TYP     Attchd   
2      COLLGCR       Norm  ...      Sbrkr          Gd        Typ     Attchd   
3      CRAWFOR       Norm  ...      Sbrkr          Gd        TYP     DETCHD   
4      Noridge       NORM  ...      Sbrkr          GD        Typ     Attchd   

  GarageFinish GarageQual GarageCond PavedDrive SaleType SaleConditi

###  Expected results:

```
Id MSZoning Street LotShape LandContour Utilities LotConfig LandSlope  \
0   1       RL   Pave      Reg         Lvl    AllPub    Inside       Gtl
1   2       RL   Pave      Reg         Lvl    AllPub       FR2       Gtl
2   3       RL   Pave      IR1         Lvl    AllPub    Inside       Gtl
3   4       RL   Pave      IR1         Lvl    AllPub    Corner       Gtl
4   5       RL   Pave      IR1         Lvl    AllPub       FR2       Gtl

Neighborhood Condition1  ... Electrical KitchenQual Functional GarageType  \
0      CollgCr       Norm  ...      SBrkr          Gd        Typ     Attchd
1 Veenker Feed R ... SCRKR TA PAY CHECKED
2      CollgCr       Norm  ...      SBrkr          Gd        Typ     Attchd
3      Crawfor       Norm  ...      SBrkr          Gd        Typ     Detchd
4      NoRidge       Norm  ...      SBrkr          Gd        Typ     Attchd

GarageFinish GarageQual GarageCond PavedDrive SaleType SaleCondition
0 RFn NOT WA
1 RFn Normal WD
2 RFn NOT WA
3 UNF TA TA Y WD ABNORML
44 RFn NOT WA

[5 rows x 39 columns]
Id MSZoning Street LotShape LandContour Utilities LotConfig LandSlope  \
1333  1456       RL   Pave      Reg         Lvl    AllPub    Inside       Gtl
1334  1457       RL   Pave      Reg         Lvl    AllPub    Inside       Gtl
1335  1458       RL   Pave      Reg         Lvl    AllPub    Inside       Gtl
1336  1459       RL   Pave      Reg         Lvl    AllPub    Inside       Gtl
1337  1460       RL   Pave      Reg         Lvl    AllPub    Inside       Gtl

Neighborhood Condition1  ... Electrical KitchenQual Functional  \
1333 Gilbert Norm ... Sbrkr take type
1334 NWAMES NORM ... SBRKR TA Min1
1335      Crawfor       Norm  ...      SBrkr          Gd        Typ
1336        NAmes       Norm  ...      FuseA          Gd        Typ
1337 Edwards norm ... SBRK TAKE TYPE

GarageType GarageFinish GarageQual GarageCond PavedDrive SaleType  \
1333 Atchd RFn RFn THE WD
1334 Attchd Unf THE WD
1335 Attchd RFn RFn THE WD
1336 Atchd Unf THE WD
1337 Atchd Fin THE WD

Salecondition
1333        Normal
1334        Normal
1335        Normal
1336        Normal
1337        Normal

[5 rows x 39 columns]
```

### Step 2

Run the code block below and try to get some insight into the data you are looking at.

In [8]:
pd_data=data.copy()
pd_data.set_index("Id",inplace=True)
pd_data

MSZoning Street LotShape LandContour Utilities LotConfig LandSlope  \
Id                                                                        
1          Rl   PAVE      Reg         Lvl    Allpub    Inside       Gtl   
2          RL   PAVE      Reg         Lvl    Allpub       FR2       Gtl   
3          Rl   Pave      Ir1         LVL    Allpub    Inside       Gtl   
4          Rl   Pave      IR1         Lvl    ALLPUB    Corner       GTL   
5          Rl   Pave      Ir1         Lvl    Allpub       Fr2       GTL   
...       ...    ...      ...         ...       ...       ...       ...   
1456       Rl   PAVE      Reg         LVL    Allpub    Inside       GTL   
1457       Rl   PAVE      REG         Lvl    Allpub    Inside       Gtl   
1458       RL   Pave      Reg         LVL    Allpub    Inside       Gtl   
1459       RL   Pave      Reg         Lvl    Allpub    Inside       Gtl   
1460       Rl   Pave      Reg         LVL    Allpub    Inside       Gtl   

     Neighborhood Condition1 Condition2  ... Electrical KitchenQual  \
Id                                       ...                          
1         COLLGCR       Norm       NORM  ...      Sbrkr          Gd   
2         Veenker      Feedr       Norm  ...      SBRKR          Ta   
3         COLLGCR       Norm       Norm  ...      Sbrkr          Gd   
4         CRAWFOR       Norm       NORM  ...      Sbrkr          Gd   
5         Noridge       NORM       Norm  ...      Sbrkr          GD   
...           ...        ...        ...  ...        ...         ...   
1456      Gilbert       Norm       NORM  ...      Sbrkr          Ta   
1457       Nwames       NORM       Norm  ...      SBRKR          TA   
1458      Crawfor       Norm       Norm  ...      Sbrkr          Gd   
1459        Names       Norm       Norm  ...      Fusea          Gd   
1460      Edwards       NORM       Norm  ...      SBRKR          Ta   

     Functional GarageType GarageFinish GarageQual GarageCond PavedDrive  \
Id                                                                         
1           TYP     Attchd          Rfn         TA         TA          Y   
2           TYP     Attchd          Rfn         Ta         TA          Y   
3           Typ     Attchd          RFN         TA         TA          Y   
4           TYP     DETCHD          UNF         Ta         Ta          Y   
5           Typ     Attchd          Rfn         TA         Ta          Y   
...         ...        ...          ...        ...        ...        ...   
1456        TYP     Attchd          Rfn         TA         Ta          Y   
1457       Min1     ATTCHD          Unf         Ta         TA          Y   
1458        Typ     Attchd          Rfn         TA         TA          Y   
1459        TYP     Attchd          Unf         Ta         TA          Y   
1460        Typ     ATTCHD          Fin         Ta         Ta          Y   

     SaleType SaleCondition  
Id                           
1          Wd        Normal  
2          Wd        Normal  
3          WD        NORMAL  
4          Wd       ABNORML  
5          WD        Normal  
...       ...           ...  
1456       Wd        Normal  
1457       Wd        Normal  
1458       Wd        NORMAL  
1459       WD        Normal  
1460       Wd        NORMAL  

[1338 rows x 38 columns]

Please implement a ```count_by_group(data,column)``` function that returns statistics by group ```column``` for column ```column``` in a ```DataFrame```. The statistics contain the number of unique values ​​in the column.

In [9]:
# Начало вашего кода
def count_by_group(data, column):
    counts = data[column].value_counts().sort_index()
    counts.name = "Lotter"
    return counts
# Конец вашего кода

In [10]:
data.groupby('LotShape').count()

Id  MSZoning  Street  LandContour  Utilities  LotConfig  LandSlope  \
LotShape                                                                        
IR1       238       238     238          238        238        238        238   
IR2        20        20      20           20         20         20         20   
IR3         6         6       6            6          6          6          6   
Ir1       221       221     221          221        221        221        221   
Ir2        20        20      20           20         20         20         20   
Ir3         4         4       4            4          4          4          4   
REG       280       280     280          280        280        280        280   
Reg       549       549     549          549        549        549        549   

          Neighborhood  Condition1  Condition2  ...  Electrical  KitchenQual  \
LotShape                                        ...                            
IR1                238         238         238  ...         238          238   
IR2                 20          20          20  ...          20           20   
IR3                  6           6           6  ...           6            6   
Ir1                221         221         221  ...         221          221   
Ir2                 20          20          20  ...          20           20   
Ir3                  4           4           4  ...           4            4   
REG                280         280         280  ...         280          280   
Reg                549         549         549  ...         549          549   

          Functional  GarageType  GarageFinish  GarageQual  GarageCond  \
LotShape                                                                 
IR1              238         238           238         238         238   
IR2               20          20            20          20          20   
IR3                6           6             6           6           6   
Ir1              221         221           221         221         221   
Ir2               20          20            20          20          20   
Ir3                4           4             4           4           4   
REG              280         280           280         280         280   
Reg              549         549           549         549         549   

          PavedDrive  SaleType  SaleCondition  
LotShape                                       
IR1              238       238            238  
IR2               20        20             20  
IR3                6         6              6  
Ir1              221       221            221  
Ir2               20        20             20  
Ir3                4         4              4  
REG              280       280            280  
Reg              549       549            549  

[8 rows x 38 columns]

In [11]:
print(count_by_group(data, "LotShape"))

IR1    238
IR2     20
IR3      6
Ir1    221
Ir2     20
Ir3      4
REG    280
Reg    549
Name: Lotter, dtype: int64


### Ожидаемый результат:

```
Lotter
IR1 459
IR2     40
IR3     10
Reg    829
Name: LotShape, dtype: int64
```

In [15]:
import pandas as pd

def count_by_group(data: pd.DataFrame, column: str = None):
    results = {}
    
    if column:  # если указана конкретная колонка
        results[column] = data[column].value_counts()
    else:  # если колонка не указана, то считаем для всех object категориальных
        for col in data.select_dtypes(include=["object"]).columns:
            results[col] = data[col].value_counts()
    
    return results

result=count_by_group(data=pd_data)
print(type(result))
print(result)

<class 'dict'>
{'MSZoning': RL       553
Rl       513
Rm        99
RM        92
FV        32
Fv        30
C all      6
Rh         6
RH         5
C ALL      2
Name: MSZoning, dtype: int64, 'Street': Pave    973
PAVE    360
GRVL      3
Grvl      2
Name: Street, dtype: int64, 'LotShape': Reg    549
REG    280
IR1    238
Ir1    221
Ir2     20
IR2     20
IR3      6
Ir3      4
Name: LotShape, dtype: int64, 'LandContour': Lvl    836
LVL    370
Bnk     38
HLS     26
Low     22
Hls     22
BNK     14
LOW     10
Name: LandContour, dtype: int64, 'Utilities': Allpub    990
ALLPUB    347
Nosewa      1
Name: Utilities, dtype: int64, 'LotConfig': Inside     733
INSIDE     224
Corner     179
Culdsac     69
CORNER      65
Fr2         26
CULDSAC     21
FR2         17
FR3          2
Fr3          2
Name: LotConfig, dtype: int64, 'LandSlope': Gtl    870
GTL    395
Mod     45
MOD     16
Sev      8
SEV      4
Name: LandSlope, dtype: int64, 'Neighborhood': Names      142
Collgcr    106
Oldtown     79
NAMES    

###  Expected results:

```
<class 'dict'>
{'MSZoning': RL         1066
RM          191
FV           62
RH           11
C (all)       8
Name: MSZoning, dtype: int64, 'Street': Pave    1333
Grvl       5
Name: Street, dtype: int64, 'LotShape': Reg    829
IR1 459
IR2     40
IR3     10
Name: LotShape, dtype: int64, 'LandContour': Lvl    1206
BNK 52
HLS      48
Low      32
Name: LandContour, dtype: int64, 'Utilities': AllPub    1337
Nome avoid 1
Name: Utilities, dtype: int64, 'LotConfig': Inside     957
Corner     244
CulDSac     90
43 difference
Fr3 4
Name: LotConfig, dtype: int64, 'LandSlope': Gtl    1265
Mod      61
Sev      12
Name: LandSlope, dtype: int64, 'Neighborhood': NAmes      209
Collgcr 146
Oldtown 100
Somerst     83
Gilbert     77
NridgHt     75
The baby 73
Edwards     70
Sawyer      69
SawyerW     53
Crawfor     50
Brxide 47
Mitchel     42
NoRidge     41
Timber      37
Idotrr 29
ClearCr     26
StoneBr     25
Swisu 20
Blmngtn     17
Brdale 15
MeadowV     12
Veenker 11
NPkVill      9
Blueste      2
Name: Neighborhood, dtype: int64, 'Condition1': Norm      1162
Feedr       63
Artery      43
RRAN 26
Poson 19
Rrae 10
Put 8
Rrn 5
RRNe         2
Name: Condition1, dtype: int64, 'Condition2': Norm      1324
Feedr        5
Artery       2
Poson 2
Rrn 2
Put 1
IRRAN 1
Rrae 1
Name: Condition2, dtype: int64, 'BldgType': 1Fam      1138
Tunhse 112
Tunhs 38
Duplex      28
2fmCon      22
Name: BldgType, dtype: int64, 'HouseStyle': 1Story    657
2Story    426
1.5pen 134
SLvl       64
SFOYER 30
1.5Unf     11
2.5Unf     10
2.5Fin 6
Name: HouseStyle, dtype: int64, 'RoofStyle': Gable      1037
Hip         272
Flat         11
Gambrel      10
Mansard 6
Shed          2
Name: RoofStyle, dtype: int64, 'RoofMatl': CompShg    1314
Tar & GRR9
Wdshngl 6
WdShake       5
Roll          1
Membrane 1
ClyTile       1
Metal         1
Name: RoofMatl, dtype: int64, 'Exterior1st': VinylSd    486
HdBoard    211
MetalSd    201
WD SDNG 183
Plywood    100
Cemntbd 52
BrkFace     44
Stucco 21
WdShing     20
AsbShng     15
Stone        2
Shimasta 1
BrkComm      1
CBlock       1
Name: Exterior1st, dtype: int64, 'Exterior2nd': VinylSd    475
MetalSd    197
HdBoard    197
WD SDNG 176
Plywood    127
CmentBd     51
Wd Shng     32
Stucco 23
BrkFace     22
AsbShng     16
Shimastak 10
Brk Cmn      6
AsphShn      2
Stone        2
CBlock       1
Other        1
Name: Exterior2nd, dtype: int64, 'MasVnrType': None       763
BrkFace    432
Stone      128
Brkcmn 15
Name: MasVnrType, dtype: int64, 'ExterQual': TA    803
Gd    477
Ex     51
Fa      7
Name: ExterQual, dtype: int64, 'ExterCond': TA    1183
Gd     137
Fa      16
Ex       2
Name: ExterCond, dtype: int64, 'Foundation': PConc     620
CBlock    580
On the Brk 129
Stone       6
Wood        3
Name: Foundation, dtype: int64, 'BsmtQual': TA    594
Gd    592
Ex    120
Fa     32
Name: BsmtQual, dtype: int64, 'BsmtCond': TA    1237
Gd      62
Fa      38
After 1
Name: BsmtCond, dtype: int64, 'BsmtExposure': No    887
Of 213
Gd    127
Mn    111
Name: BsmtExposure, dtype: int64, 'BsmtFinType1': GLQ    402
Unf    392
Alq 209
Fir 141
Rec    125
LWQ 69
Name: BsmtFinType1, dtype: int64, 'BsmtFinType2': Unf    1176
Rec      53
Lwq 46
Fir 32
Alq 19
GLQ      12
Name: BsmtFinType2, dtype: int64, 'Heating': GasA    1318
Neat 16
Grav       3
OTH 1
Name: Heating, dtype: int64, 'HeatingQC': Ex    704
By 380
Gd    217
Fa     36
After 1
Name: HeatingQC, dtype: int64, 'CentralAir': Y    1277
N      61
Name: CentralAir, dtype: int64, 'Electrical': SBrkr    1242
FOUNA 76
FuseF      17
FuseP       2
Mix         1
Name: Electrical, dtype: int64, 'KitchenQual': TA    650
Gd    568
Ex     97
Fa     23
Name: KitchenQual, dtype: int64, 'Functional': Typ     1254
With us 30
Min1 28
Mod       11
Maj 1 10
Maj2 4
Sev        1
Name: Functional, dtype: int64, 'GarageType': Attchd     852
Dectering 369
BuiltIn     85
Basment     19
CarPort      7
2Types       6
Name: GarageType, dtype: int64, 'GarageFinish': Unf    580
West Germany 413
Fin    345
Name: GarageFinish, dtype: int64, 'GarageQual': TA    1270
Fa      48
Gd      14
After 3
Ex       3
Name: GarageQual, dtype: int64, 'GarageCond': TA    1287
Fa      33
Gd       9
After 7
Ex       2
Name: GarageCond, dtype: int64, 'PavedDrive': Y    1257
N      54
P      27
Name: PavedDrive, dtype: int64, 'SaleType': WD       1158
New       117
COD        42
ConLD       6
Conlw 4
Congi 4
CWD         4
Con         2
Oth         1
Name: SaleType, dtype: int64, 'SaleCondition': Normal     1104
Partial     120
Abnorml      86
Family       20
Alloca 7
Adjland 1
Name: SaleCondition, dtype: int64}
```

### Step 3

You are given the ```dirty_str_house_prices.csv``` data. Your goal is to clean it using methods provided by ```pandas``` such as ```DataFrame.apply()```, ```DataFrame.str.lower()```, etc. Any non-alphanumeric characters can be considered noise.

**Please be careful when exploring the data.**

In [16]:
# Начало вашего кода
import pandas as pd
import re

dirty_data = pd.read_csv("dirty_str_house_prices.csv")
dirty_data.set_index("Id", inplace=True)
if "Unnamed: 0" in dirty_data.columns:
    del dirty_data["Unnamed: 0"]

for col in dirty_data.select_dtypes(include="object"):
    dirty_data[col] = (
        dirty_data[col]
        .astype(str)            
        .str.strip()            
        .str.replace(r"[^a-zA-Z0-9\s]", "", regex=True)  
        .str.lower()          
    )
# Конец вашего кода

print(dirty_data)

     MSZoning Street LotShape LandContour Utilities LotConfig LandSlope  \
Id                                                                        
1          rl   pave      reg         lvl    allpub    inside       gtl   
2          rl   pave      reg         lvl    allpub       fr2       gtl   
3          rl   pave      ir1         lvl    allpub    inside       gtl   
4          rl   pave      ir1         lvl    allpub    corner       gtl   
5          rl   pave      ir1         lvl    allpub       fr2       gtl   
...       ...    ...      ...         ...       ...       ...       ...   
1456       rl   pave      reg         lvl    allpub    inside       gtl   
1457       rl   pave      reg         lvl    allpub    inside       gtl   
1458       rl   pave      reg         lvl    allpub    inside       gtl   
1459       rl   pave      reg         lvl    allpub    inside       gtl   
1460       rl   pave      reg         lvl    allpub    inside       gtl   

     Neighborhood Condit

###  Expected results:

```
MSZoning  Street LotShape LandContour Utilities   LotConfig LandSlope  \
Id
1         rl:   PAVE.     ;REg       \tlvl   AllPub.     InsidE:      gtl
2       ...RL   <PAVE    reg\t        Lvl;  AllPUb\t        FR2       Gtl<
3        ;Rl    Pave      ir1?        LVL!   Allpub!    ?inside     ...Gtl
4          rl   pave.     ;IR1        .Lvl  ;ALLPUB;     >Corner      ;GTL
5       .rl\t  PaVE\t   Ir1...        Lvl<   !Allpub        ?fr2   .GTL...
...       ...     ...      ...         ...       ...         ...       ...
1456      ?rl   PAVE>   ...Reg       >LVL<  Allpub\t  ...INSIDe:      GTL;
1457      Rl<   <PAVE      REG      ...lvl   Allpub:     .INsIDE      Gtl.
1458      ?RL   Pave!   ...Reg        >LVL   AlLPUb.     !InSiDE      >GTl
1459     RL\t   PAvE<     reg;      ?lvl\t   .AlLPUb     Inside:      :Gtl
1460     .rl!  <Pave:     Reg;     ...LVL?  .AlLPUb      INsIDe.    gtl...

Neighborhood Condition1 Condition2  ... Electrical KitchenQual  \
Id                                       ...
1        COLLGCR<      norm;      NORM.  ...     SBRKr         gd\t
2 Veenker \ T? Feedr.      ; norm ... \ tsbrk to?
3        ?COLLGCR      !Norm     .norm>  ...     sbrkr<         .Gd
4        .CRAWFOR       NORm      NORM:  ...    \tSbrkr         Gd<
5       ?NoRIdge>   ...NORM<      Norm;  ...    \tSbrkr         GD;
...           ...        ...        ...  ...        ...         ...
1456 \ Tgilbert: Norm?       NORM ...> SBRKR .TA
1457 ... NWAMES NORM ... \ TNORM ... SBRKR TA!
1458    >CRAWfoR<       Norm    Norm...  ...     Sbrkr;         !Gd
1459        names       norm    \tnorm.  ...   \tFUseA:         Gd!
1460    \tEdwards    !NORM\t      norm?  ...    ;SBRKR?        ;ta:

Functional GarageType GarageFinish GarageQual GarageCond PavedDrive  \
Id
1 TYP attent, \ttTA)
2 ;TYP Attchdd> RF\t >TE >TAt ;
3 typs ... Event;         ; Rfn \ tta ... Ta y
4 !TY DETCHD… UNF?      \tLate        ; Yes
<Typ\t\t <Typd\t <Typd\t There is a glory
...         ...        ...          ...        ...        ...        ...
1456 !TY PRAIT< :RFs HATil.
1457 MI1?    ATTCHD< :unf ?TA>
1458 :TyP.Rfn >Rfn >TA: .Ye
1459 TYP TYP.          Unf :Yes;       \tTA ...These
1460 typ: .ATTCHD FIn > is?      \tta< >...

Saletype salecondition
Id
1         wd      \tNormal?
2         Wd        Normal.
3         WD;        NORMAL
4         wd.     ABNORML\t
5        ?WD!       NoRmAl>
...       ...           ...
1456      Wd?     normal...
1457      Wd;     \tNormal;
1458     >wd!      :NORMAL;
1459     <WD!       :normal
1460      Wd;       ;NORMAL

[1338 rows x 38 columns]
```

In [17]:
pd_dirty_data=dirty_data.copy()

In [18]:
st1 = '..ST'
st2 = '.KZ'

In [19]:
def dirty_data(data):
    for col in data.select_dtypes(include="object"):
        data[col] = (
            data[col]
            .astype(str)
            .str.strip()
            .str.replace(r"[^a-zA-Z0-9]", "", regex=True)
            .str.upper()
        )
    return data

pd_dirty_data = dirty_data(pd_dirty_data)
print(pd_dirty_data.head())

   MSZoning Street LotShape LandContour Utilities LotConfig LandSlope  \
Id                                                                      
1        RL   PAVE      REG         LVL    ALLPUB    INSIDE       GTL   
2        RL   PAVE      REG         LVL    ALLPUB       FR2       GTL   
3        RL   PAVE      IR1         LVL    ALLPUB    INSIDE       GTL   
4        RL   PAVE      IR1         LVL    ALLPUB    CORNER       GTL   
5        RL   PAVE      IR1         LVL    ALLPUB       FR2       GTL   

   Neighborhood Condition1 Condition2  ... Electrical KitchenQual Functional  \
Id                                     ...                                     
1       COLLGCR       NORM       NORM  ...      SBRKR          GD        TYP   
2       VEENKER      FEEDR       NORM  ...      SBRKR          TA        TYP   
3       COLLGCR       NORM       NORM  ...      SBRKR          GD        TYP   
4       CRAWFOR       NORM       NORM  ...      SBRKR          GD        TYP   
5       

### Expected results:

```
MSZoning Street LotShape LandContour Utilities LotConfig LandSlope  \
Id
1          RL   PAVE      REG         LVL    ALLPUB    INSIDE       GTL
2          RL   PAVE      REG         LVL    ALLPUB       FR2       GTL
3          RL   PAVE      IR1         LVL    ALLPUB    INSIDE       GTL
4          RL   PAVE      IR1         LVL    ALLPUB    CORNER       GTL
5          RL   PAVE      IR1         LVL    ALLPUB       FR2       GTL
...       ...    ...      ...         ...       ...       ...       ...
1456       RL   PAVE      REG         LVL    ALLPUB    INSIDE       GTL
1457       RL   PAVE      REG         LVL    ALLPUB    INSIDE       GTL
1458       RL   PAVE      REG         LVL    ALLPUB    INSIDE       GTL
1459       RL   PAVE      REG         LVL    ALLPUB    INSIDE       GTL
1460       RL   PAVE      REG         LVL    ALLPUB    INSIDE       GTL

Neighborhood Condition1 Condition2  ... Electrical KitchenQual  \
Id                                       ...
1         COLLGCR       NORM       NORM  ...      SBRKR          GD
2 Veenker Feed Spring ... Sbrk TA
3         COLLGCR       NORM       NORM  ...      SBRKR          GD
4         CRAWFOR       NORM       NORM  ...      SBRKR          GD
5         NORIDGE       NORM       NORM  ...      SBRKR          GD
...           ...        ...        ...  ...        ...         ...
1456      GILBERT       NORM       NORM  ...      SBRKR          TA
1457 NWAMES NORM NORM ... SBRKR TA
1458      CRAWFOR       NORM       NORM  ...      SBRKR          GD
1459        NAMES       NORM       NORM  ...      FUSEA          GD
1460 Edwards Norm Norm ... Patience Ta

Functional GarageType GarageFinish GarageQual GarageCond PavedDrive  \
Id
1 TYP ATCHD ATCHD ATCHD AND
2 ATTCHD RFN ATCHD ATCHD AND
3 TYP ATCHD ATCHD ATCHD AND
4 TYP DETCHD UNF THE ONF THE
5 TYP ATCHD ATCHD ATCHD AND
...         ...        ...          ...        ...        ...        ...
1456 TYP ATCHD RFN ATCHD AT
1457 min1 Attchd UNF TA Y Y
1458 TYP ATCHD RFN ATCHD AT
1459 TYP ATCHD ATCHD THE AND
1460 TYP ATCHD FING THE

Saletype salecondition
Id
1          WD        NORMAL
2          WD        NORMAL
3          WD        NORMAL
4          WD       ABNORML
5          WD        NORMAL
...       ...           ...
1456       WD        NORMAL
1457       WD        NORMAL
1458       WD        NORMAL
1459       WD        NORMAL
1460       WD        NORMAL

[1338 rows x 38 columns]
```

### Step 4

After cleaning ```pd_dirty_data```, compare it with ```pd_data```. Do we need to make some changes to ```pd_data``` or/and ```pd_dirty_data``` to make a fair comparison? Implement ```compare_dataframes(pd_data, pd_dirty_data)``` function that will compare input ```DataFrames```.

In [20]:
# Начало вашего кода
def compare_dataframes(pd_data, pd_dirty_data):
    df1 = pd_data.copy()
    df2 = pd_dirty_data.copy()
    
    df2 = df2[df1.columns]
    
    for col in df1.select_dtypes(include="object"):
        df1[col] = df1[col].astype(str).str.strip().str.upper()
        df2[col] = df2[col].astype(str).str.strip().str.upper()
    
    percent_same = (df1 == df2).sum() / len(df1) * 100
    
    return percent_same
# Конец вашего кода

print(compare_dataframes(pd_data, pd_dirty_data))

MSZoning          99.402093
Street           100.000000
LotShape         100.000000
LandContour      100.000000
Utilities        100.000000
LotConfig        100.000000
LandSlope        100.000000
Neighborhood     100.000000
Condition1       100.000000
Condition2       100.000000
BldgType         100.000000
HouseStyle       100.000000
RoofStyle        100.000000
RoofMatl         100.000000
Exterior1st       86.322870
Exterior2nd       84.005979
MasVnrType       100.000000
ExterQual        100.000000
ExterCond        100.000000
Foundation       100.000000
BsmtQual         100.000000
BsmtCond         100.000000
BsmtExposure     100.000000
BsmtFinType1     100.000000
BsmtFinType2     100.000000
Heating          100.000000
HeatingQC        100.000000
CentralAir       100.000000
Electrical       100.000000
KitchenQual      100.000000
Functional       100.000000
GarageType       100.000000
GarageFinish     100.000000
GarageQual       100.000000
GarageCond       100.000000
PavedDrive       100

### Expected results:

```
(%) same
Mszoning 100,000000
Street         100.000000
Lotshepage 100.000000
LandContour    100.000000
Utilities      100.000000
LotConfig      100.000000
LandSlope      100.000000
Neighborhood   100.000000
Condition1 100.000000
Condition2     100.000000
BldgType       100.000000
HouseStyle      87.967115
ROOF STYLE 100.000000
RoofMatl       100.000000
Exterior1st    100.000000
Exterior2nd    100.000000
MasVnrType     100.000000
ExterQual      100.000000
ExterCond      100.000000
Foundation     100.000000
BsmtQual       100.000000
BsmtCond       100.000000
BsmtExposure   100.000000
BsmtFinType1   100.000000
BsmtFinType2   100.000000
Heating        100.000000
HeatingQC      100.000000
CentralAir     100.000000
Electrical     100.000000
KitchenQual    100.000000
Functional     100.000000
Garage type 100.000000
GarageFinish   100.000000
GarageQual     100.000000
GarageCond     100.000000
PavedDrive     100.000000
SaleType       100.000000
Salecondition 100.000000
```

# Good Job!